# ----------------------------
# Makefile Options
# ----------------------------

NAME = SPACEMAN
ICON = iconc.png
DESCRIPTION = "Horizontal shootemup"
COMPRESSED = YES
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)