# ----------------------------
# Makefile Options
# ----------------------------

NAME = SOLITAIR
ICON = iconc.png
DESCRIPTION = "Solitair but just the end animation"
COMPRESSED = YES
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)