# ----------------------------
# Makefile Options
# ----------------------------

NAME = DVDASM
ICON = iconc.png
DESCRIPTION = "Bouncing DVD Logo"
COMPRESSED = YES
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)